.flake8
API.md
jaxtyping/__init__.py
jaxtyping/array_types.py
jaxtyping/decorator.py
jaxtyping/import_hook.py
setup.py
test/test_array.py

Closes #8.
Closes #9.
Closes #10.

Version 0.1.0

---

jaxtyping/array_types.py

Following #19 -- thanks @jonkhler!

Fix for boolean checking not working

---

jaxtyping/__init__.py
jaxtyping/array_types.py
jaxtyping/decorator.py
jaxtyping/pytree_type.py
test/test_decorator.py

Fixed jaxtyped breaking descriptors. Fixed long module names.

---

jaxtyping/__init__.py
jaxtyping/array_types.py
jaxtyping/pytree_type.py
test/test_threading.py

More fixes

---

MANIFEST.in
jaxtyping/__init__.py
setup.py

Fixed py.type not being packaged

---

jaxtyping/pytree_type.py

Silenced warning

---

jaxtyping/__init__.py
jaxtyping/decorator.py
setup.py

solves https://github.com/google/jaxtyping/issues/43

update jaxtyped decorator

---

jaxtyping/import_hook.py
test/import_hook_tester_beartype.py
test/import_hook_tester_broken_checker.py
test/import_hook_tester_typeguard.py

Fix vanilla dataclasses

---

jaxtyping/_import_hook.py
pyproject.toml

Hash is now stable across python runtimes

---

docs/api/runtime-type-checking.md
pyproject.toml

The IPython extension was added in #112.

Document IPython extension and version bump

---

jaxtyping/_import_hook.py

Fix install_import_hook(..., None)

---

docs/api/array.md
jaxtyping/_array_types.py
jaxtyping/_decorator.py
jaxtyping/_import_hook.py
jaxtyping/_pytree_type.py
jaxtyping/_raise.py
jaxtyping/_storage.py
test/test_array.py
test/test_decorator.py
test/test_messages.py

Fixed new-style PRNG keys.

---

docs/api/array.md

Correct pytree path in array.md

Correct pytree path in array.md

---

jaxtyping/_decorator.py
test/test_decorator.py

Bind default arguments

---

jaxtyping/_array_types.py
pyproject.toml

Version 0.2.29

---

jaxtyping/_array_types.py

Fix misleading error message

---

jaxtyping/_array_types.py

Compatibility with ray.

---

.pre-commit-config.yaml
jaxtyping/_decorator.py
jaxtyping/_pytree_type.py
jaxtyping/_typeguard/LICENSE
jaxtyping/_typeguard/README.md
jaxtyping/_typeguard/__init__.py
pyproject.toml
test/test_array.py
test/test_decorator.py
test/test_pytree.py

+Bumping the ruff version whilst we're here.

Now vendoring typeguard v2.13.3

---

jaxtyping/_decorator.py

Now statically working with dataclasses correctly.

---

.pre-commit-config.yaml
test/types/decorator.py

Fixes https://github.com/patrick-kidger/jaxtyping/issues/275.

Pre-commit hooks for pyright and mypy (only API tests)
