jaxtyping/array_types.py
Turns out that python3.8, Union lacks the __name__ attribute.  Use repr() in these cases.
=> Add support for e.g. jaxtyping.Float[Union[...], ...] in py3.8

test/test_pytree.py
Added `test_pytree_namedtuple` to `test/test_pytree.py` which tests NamedTuple subclasses with the PyTree type check.
=> NamedTuple example

jaxtyping/__init__.py
Bit mysterious that this worked before, really. I've tested this fix as best I can against the various static type checkers, but these are weird and varied enough that this might not be a perfect fix.
If you see this and have issues, let me know.
=> Hopefully fixed PyTree raising spurious errors.

jaxtyping/__init__.py
Doing this silences a *whole heap* of Pyright warnings that all say "Illegal type annotation: variable not allowed unless it is a type alias"
=> Add TypeAlias decoration to PyTree

.github/workflows/release.yml, .github/workflows/run_tests.yml, CONTRIBUTING.md, jaxtyping/__init__.py, jaxtyping/array_types.py, test/test_array.py, test/test_serialisation.py
This required quite a lot of refactoring! JAX supports virtual subclass registration (its metaclass is ABCMeta) but NumPy does not, so we have to actually subclass `np.ndarray`. Simple stuff like __base__ hacking fails due to deallocator conflicts.
=> We now have `Float[np.ndarray, ...] <: np.ndarray`. Added basic torch tests.

API.md, jaxtyping/__init__.py, jaxtyping/array_types.py, test/test_array.py
- Added support for functions in symbolic dimensions, e.g. "min(foo,bar)", which were previously disallowed due to the presence of a comma. (#51)
- Added support for adding ignored names to dimensions, e.g. "cols=4". (#76)
- Added support for Python 3.10 A | B union types (#73)
=> Some improvements

jaxtyping/_array_types.py, jaxtyping/_decorator.py
- jaxtyping no longer appears in tracebacks
- Compatibility with JAX changes to opaque dtypes
=> dtype compat

docs/api/array.md, jaxtyping/_array_types.py
See https://github.com/google/jax/pull/17297
=> Updated to support both new and old style JAX PRNG keys, as they are going to co-exist simultaneously.

jaxtyping/__init__.py, jaxtyping/_ipython_extension.py, test/requirements.txt, test/test_ipython_extension.py
Making jaxtyping an IPython extension, so that import hooks can be used in IPython notebooks with minimal effort.
Example usage:
```
import jaxtyping
%load_ext jaxtyping
```
Much better than the original solution for #96
=> Make jaxtyping an IPython extension

test/test_import_hook.py
Fixing #121 .
I spent a bit of time trying to figure out what is wrong, and discovered that importlib had some issues. Instead of figuring out what exactly is the problem, I am just invalidating caches..
=> Fix flakiness of transitive import hook test

.pre-commit-config.yaml
Noticed that the versions are almost a year old. Also this (might) fix a warning in GitHub actions.
=> Bump up pre-commit ruff and black versions

jaxtyping/_import_hook.py, jaxtyping/_ipython_extension.py, test/conftest.py, test/test_import_hook.py, test/test_ipython_extension.py
Hi, Patrick! 
I discovered an interesting problem, that is, while not being extremely critical, leads to meaningless error messages, and almost impossible to debug. While it could happen with any typechecker, it does not happen with typeguard, though happens with beartype. Here is a sample code:
```
import jaxtyping
%load_ext jaxtyping
%jaxtyping.typechecker beartype.beartype
#%% cell separation, so that hook can be applied
from beartype import *
def f(x: int):
...
f(1)
```
throws ```AttributeError: 'function' object has no attribute 'beartype'```
The reason for this is that when importing the beartype only the module is imported, so the annotation looks like ```@beartype.beartype```. The import of hook by beartype is done on top of the file/cell, thus any imports done inside file/cell …
=> Fix a bug with an explicit typechecker import using hook

jaxtyping/__init__.py, jaxtyping/_decorator.py, jaxtyping/_import_hook.py, test/import_hook_tester.py
Previously, using the import hook with dataclasses resulted in the `__init__` method of the dataclass being checked.
This was undesirable when using `eqx.field(converter=...)`, as the annotation didn't necessarily reflect the argument type.
A typical example was
```python
class Foo(eqx.Module):
x: jax.Array = eqx.field(converter=jnp.ndarray)
Foo(1)  # 1 is not an array! But this code is valid.
```
After this change, we instead monkey-patch our checks to happen at the end of the `__init__` of the dataclass -- after conversion has run.
Note that this requires https://github.com/patrick-kidger/equinox/pull/524. Otherwise, Equinox does conversion too late (in `_ModuleMeta.__call__`, after `__init__` has been run).
(This is also the reason for the test failure at the moment, which is spurious …
=> dataclasses now have fields checked, not __init__.

pyproject.toml
Hi Patrick,
I noticed that in ```pyproject.toml``` there is no constraint on the highest allowed version of typeguard, eventhough it looks like there should be. [PEP 508](https://peps.python.org/pep-0508/) explains how does version notation work, and thus I just introduced this constraint.
=> Allow only typeguard lower than 3.x.x version

jaxtyping/_array_types.py, jaxtyping/_decorator.py, test/test_array.py, test/test_decorator.py
Previously, something like this would not raise an error, as
variadic+broadcast dimensions were stored in a separate namespace to
variadic+nonbroadcast dimensions:
```python
def f(x: Float[Array, "*foo"], y: Float[Array, "#*foo"]):
pass
a, b = ...
assert a.shape == (3, 4)
assert b.shape == (5,)
f(a, b)
```
=> Fixed mixing variadic+broadcast with variadic+nonbroadcast dimensions.

README.md, docs/api/array.md, docs/api/runtime-type-checking.md, docs/index.md, jaxtyping/__init__.py, jaxtyping/_array_types.py, jaxtyping/_decorator.py, jaxtyping/_import_hook.py, jaxtyping/_pytree_type.py, jaxtyping/_raise.py, jaxtyping/_storage.py, test/conftest.py, test/test_array.py, test/test_decorator.py, test/test_messages.py, test/test_pytree.py
Phew, this ended up being a pretty complicated change!
The basic summary is that we now support the syntax
```
@jaxtyped(typechecker=typechecker)
def f(...): ...
```
and when using this, we now get pretty error messages about what went
wrong.
(
The old syntax, i.e.
```
@jaxtyped
@typechecker
def f(...): ...
```
is still supported, but doesn't give much information.
)
The internals of this do quite a lot of magic! In particular we
dynamically create quite a lot of functions and test the provided
arguments against their signatures. The overhead should still be
minimal under `jax.jit`, though.
(TODO: what's the overhead like in non-jit situations, e.g. PyTorch?
I've tried to minimise the overhead throughout just to be sure, but
perhaps PyTorch users should stick to the old syntax?)
=> Pretty error messages: fixes #6.

jaxtyping/_decorator.py
Hello!
This is a small PR to fix typos in docstrings.
Maybe, I would suggest adding an import for `dataclass` in the example (otherwise it will not run), and maybe indicate that it works with other dataclass decorators, like the `dataclass` decorator from chex.
=> chore(docs): fix typos in docstrings

jaxtyping/_decorator.py
@jeertmans -- updated the dataclass docs as suggested in #154. In practice I'm recommending `equinox.Module` rather than `chex.dataclass`, as it's a bit safer for most purposes + it's part of the same tech stack as jaxtyping / etc.
=> Update dataclass docs

jaxtyping/_array_types.py
Recall that jaxtyping will currently generate rich error messages in precisely one scenario: about the arguments and return types when doing:
```python
@jaxtyped(typechecker=beartype)
def foo(...): ...
```
With this commit we add support for beartype 0.17.0's pseudo-standard `__instancecheck_str__`, which allows us to report exactly *why* an `instancecheck` failed -- was the shape of the array wrong, was the dtype wrong, etc?
This means the following:
1. For those using beartype decorators, the following will *also* generate an informative error message, and moreover it will state exactly why (shape mismatch, dtype mismatch etc):
```python
@jaxtyped(typechecker=None)
@beartype
def foo(...): ...
```
(In practice we probably won't recommend the above combination in the docs just to keep …
=> Added support for beartype 0.17.0's __instancecheck_str__.

jaxtyping/_array_types.py, jaxtyping/_decorator.py, test/requirements.txt, test/test_array.py, test/test_decorator.py, test/test_equals.py, test/test_generators.py, test/test_no_jax_dependency.py, test/test_serialisation.py
Hey Patrick,
I was just looking through the issues, and discovered that there is #91, which states that generators do not work. I just checked, and seemingly they work on the current version, but just in case I added a simple test to make sure that typechecking generators will continue to work in the future. It is not the original test, but I guess it is close enough imitation that does not involve torch.
=> Adding a test for generator support

jaxtyping/_array_types.py
`__instancecheck_str__` raises an exception from message formatting in a specific case of variadic shape mismatch.
This causes type checkers to raise exceptions, rather than properly type check, at runtime.
This is reproduced via:
```
import numpy as np
from jaxtyping import Shaped
ta = np.arange(3 * 10).reshape((3, 10))
isinstance(ta, Shaped[np.ndarray, "*p b c"])
isinstance(ta[0], Shaped[np.ndarray, "*p b c"])
```
for the error:
```
Traceback (most recent call last):
File "/workspaces/jaxtyping/repro.py", line 11, in <module>
isinstance(ta[0], Shaped[np.ndarray, "*p b c"])
File "/workspaces/jaxtyping/jaxtyping/_array_types.py", line 156, in __instancecheck__
return cls.__instancecheck_str__(obj) == ""
File "/workspaces/jaxtyping/jaxtyping/_array_types.py", line 205, in …
```
=> Fix _check_shape str formatting for variadics

jaxtyping/_decorator.py
See https://github.com/patrick-kidger/jaxtyping/issues/188#issuecomment-1984247889.
=> Fix `jax` dependency issue when `jaxlib` is not installed.

jaxtyping/_array_types.py
Hi!
I use `tensorflow==2.9.1` and I came across a situation where `tf.Tensor` could not have `ndim` attribute at some point of execution. Moreover, what I found out is that the problem does not occur in `tensorflow==2.16`. 
Here you have a simple code to reproduce the error. 
```
import tensorflow as tf
import jaxtyping as jax
import beartype
@tf.function()
@jax.jaxtyped(typechecker=beartype.beartype)
def map_function(tensor: jax.Float[tf.Tensor, "h w c"]) -> jax.Float[tf.Tensor, "h w c"]:
return 1 - tensor
def main():
tf.config.run_functions_eagerly(True)
tf.data.experimental.enable_debug_mode()
dataset = tf.data.Dataset.from_tensor_slices(tensors=tf.random.uniform((100,30,30,3)))
dataset = dataset.map(map_function)
if __name__ == "__main__":
main()
```
This is what i get …
=> Replace ndim with len(shape)

jaxtyping/_ipython_extension.py
IPython is quite a chunky package, and importing it unconditionally makes jaxtyping itself relatively slow to import.
=> Define the IPython magic lazily

jaxtyping/__init__.py, jaxtyping/_array_types.py, test/test_array.py
=> Add support for numpy struct dtype

test/test_no_jax_dependency.py, test/test_pytree.py
https://github.com/google/jax/pull/19930 deprecated `jax.tree_map` in favor of `jax.tree.map`.
Additionally, this adds some configuration to skip tests that depend on `sys.executable` in environments where it is not set.
=> Update deprecated method usage

jaxtyping/_decorator.py, test/test_array.py, test/test_decorator.py, test/test_generators.py
=> typeguard warnings, on not having any annotations, now name the correct function.

.pre-commit-config.yaml, jaxtyping/_decorator.py
This commit does two things.
First of all, it fixes a bug in which we forgot to add in default arguments when calling `_get_problem_arg`. This meant that in practice, if you had a default argument, then the very first argument would be what is reported.
Second, it rearranges things into a couple of extra stack frames, for an easier debugging experience.
- When looking at the main error message, this will now occur on the line that actually raised it, and not the `finally: pop_stack_memo()` line.
- The argument-specific `_get_problem_arg` error is what is now attached as the cause, rather than the overall failure of the whole typechecking.
=> Improved localisation of errors to particular arguments.

CONTRIBUTING.md, jaxtyping/_import_hook.py, test/requirements.txt
Also updated `CONTRIBUTING.md` to install the test requirements file, and replaced `jaxlib` with `jax` in that requirements file since they're bundled together now (+ `jax` isn't necessarily installed in the env for `jaxtyping` to work, but is needed for tests).
=> Replace `ast.Str` with `ast.Constant` (deprecation warning raised in python 3.12)

pyproject.toml
It is currently impossible to add jaxtyping to a modern Python project using Poetry, because the current pyproject.toml says that it only supports Python 3.9
This PR fixes this
=> Allow Python versions higher than 3.9

jaxtyping/_decorator.py, test/test_decorator.py
The version of TypeGuard that JaxTyping depends on grabs the calling frame's locals using `sys._getframe(1).f_locals`, and returns a wrapping function that holds a reference to these locals. JaxTyping currently calls the typechecker from a frame that contains some locals. Of these, `full_fn` and `param_fn` are problematic because they, in combination with what TypeGuard is doing, end up creating reference cycles.
This commit calls the typechecker from an isolated frame in JaxTyping. This means `f_locals` of the calling frame doesn't contain anything that can end up creating cycles.
It's somewhat debatable whether this should be considered a TypeGuard problem, but I think it would be tricky to fix there. TypeGuard appears to need a mutable version of the locals to see forward defined …
=> Call typechecker from isolated frame

jaxtyping/_decorator.py, pyproject.toml
Fixes #269 using the `typing_extensions` backport.
=> Add typing_extensions to allow usage of ParamSpec in python < 3.10

jaxtyping/_array_types.py, pyproject.toml, test/test_serialisation.py
=> Added support for pickling jaxtyping annotations.
